AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless API for creating VPCs

Resources:
  VPCRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VPCRecords
      AttributeDefinitions:
        - AttributeName: vpc_id
          AttributeType: S
      KeySchema:
        - AttributeName: vpc_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VPCLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VPCManager
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref VPCRecordsTable
      Policies:
        - AmazonEC2FullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref VPCRecordsTable
      Events:
        CreateVPCAPI:
          Type: Api
          Properties:
            Path: /create-vpc
            Method: post
        GetVPCAPI:
          Type: Api
          Properties:
            Path: /get-vpc
            Method: get


